title: Fredrik Erlandsson
logo: /assets/img/fer.jpg
description: PhD in Computer science. 
show_downloads: false
google_analytics: UA-13197481-5
theme: jekyll-theme-minimal
permalink: /:categories/:title/

collections:
  academia:
    output: true
    permalink: /:collection/:title/
    order:
      - intro.md
      - publications.md
      - teaching.md

social:
    - icon: fab fa-twitter
      link: "https://twitter.com/fredrikerl"
    - icon: fab fa-linkedin
      link: "https://www.linkedin.com/in/fredrikerl"
    - icon: fab fa-github
      link: "https://github.com/fredrike"
    - icon: ai ai-cv ai-1.7x
      link: "/FredrikErlandsson.pdf"

academic_social:
    - icon: ai ai-google-scholar ai-1.7x
      link: "https://scholar.google.se/citations?user=vJjq9LwAAAAJ&h=en"
    - icon: ai ai-orcid ai-1.7x
      link: "https://orcid.org/0000-0003-3219-9598"

share:
  twitter_username: fredrikerl 

urls:
    - text: Academia
      url: /academia/
    - text: Projects
      url: /projects/
    - text: CV
      url: /FredrikErlandsson.pdf
    # - text: Interesting links
    #  url: /links

